#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;

use Glyph;
use Lexicon;
use Word;
use Parser;

my $lex = Lexicon->new();
$lex->{verbose} = 0;




#my $vehicle = Glyph->new("vehicle");
$lex->add("null");
$lex->add("animal");
$lex->add("vertebrate", "animal");
$lex->add("mammal", "vertebrate");
$lex->add("canid", "mammal");
$lex->add("dog", "canid");
$lex->add("fox", "canid");
$lex->add("jackal", "canid");
$lex->add("coyote", "canid");
$lex->add("felid", "mammal");
$lex->add("cat", "felid");
$lex->add("lion", "felid");
$lex->add("tiger", "felid");
$lex->add("jaguar", "felid");
$lex->add("leopard", "felid");
$lex->add("caracal", "felid");
$lex->add("primate", "mammal");
$lex->add("monkey", "primate");
$lex->add("howler", "monkey");
$lex->add("capuchin", "monkey");
$lex->add("babboon", "monkey");
$lex->add("ape", "primate");
$lex->add("chimpanzee", "ape");
$lex->add("gorilla", "ape");
$lex->add("orangutan", "ape");
$lex->add("human", "ape");

my $sym  = $lex->get("human");
print Dumper \$sym;
my $sym2 = $lex->get("ape");
print Dumper $sym2;
my $sym3 = $lex->get("felid");
print Dumper $sym3;

if ($sym) {
	print $sym->is("human")  . "=1\n";	#true
	print $sym->is($sym)     . "=1\n";	#true
	print $sym->is("ape")    . "=0\n";	#false
	print $sym->is($sym2)    . "=0\n";	#false
	print $sym->isa("ape")   . "=1\n";	#true
	print $sym->isa($sym2)   . "=1\n";	#true
	print $sym->isa("felid") . "=0\n";	#false
	print $sym->isa($sym3)   . "=0\n";	#false
	print $sym->isa("animal"). "=1\n";	#false
}

#my $car = Glyph->new("car", "vehicle");

#print "Lex count: " . $lex->count() . "\n";
print $lex->list() . "\n";
$lex->write();

#print "$sym\n";

#print $sym->{id}   . "\n";
#print $sym->{name} . "\n";

#$sym2->add(Glyph->new("Delta"));
#$sym->add($sym2);
#$sym->add(Glyph->new("gamma"));
#print "$sym\n";

#$lex->add($sym);
#$lex->add($sym2);
#$lex->add($sym);
#print Dumper $sym2;
#$lex->add($sym2);


#print Dumper $lex->get($sym);
#print Dumper $lex->get("beta");
#print Dumper $lex->get("gamma");




my $input = "the boy dropped the ball";
my $parser = Parser->new();
my @wordsx = $parser->process($input);

#print "result:\n" . Dumper($parser->words) . "\n";
#print "Word count: " . $parser->wordcount . "\n";

foreach my $word ($parser->words) {
#    print "\n";
#    $word->Dump();
}


print "\n\n";
